### ISSUE TITLE
plugin added - but not the accessory

### ISSUE THREAD

**Issue by alon112** [moodoapplication/homebridge-moodo#15]
hey, i don't see the accessory, added via hoobs.
follow the instructions. but i don't see after.

help please.

**Comment by lukasroegner** [comment]
@alon112 Please share your config (without personal information) and the logs from Hoobs here, so that I can check whether there is a configuration issue.

**Comment by alon112** [comment]
this is the config https://imgur.com/KPTAHn3
this is the log file https://drive.google.com/drive/folders/10QhQ-O1UH_D2IQiSVxs8UwdKCtNtLOfy?usp=sharing

thank you

**Comment by lukasroegner** [comment]
Your ring plugin seems to throw unhandled exception, which may be the cause of the Moodo plugin not starting properly. Please try to fix the issues with the ring plugin, then we can check it again.

**Comment by alon112** [comment]
i removed now ring plugin and uploaded the new log file, you can check please.

**Comment by lukasroegner** [comment]
The issue is that the `devices` property is not configured properly. The property is an array of objects, your screenshot contains the complete config in the devices field. I don't know how Hoobs displays the configuration, however, I think it is based on `homebridge-config-ui-x`. In `homebridge-config-ui-x`, the visual configuration looks like this:

<img width="843" alt="Bildschirmfoto 2020-04-24 um 09 10 29" src="https://user-images.githubusercontent.com/16758848/80184865-a9d08a00-860b-11ea-8022-8b06c7caeb3e.png">

**Comment by alon112** [comment]
Thanks, i succeeded only by the Homemanager app for ios.
problem solved!

**Comment by alon112** [comment]
another issue, possible its not support old iPad this plugin?
generation 3-4.

**Comment by lukasroegner** [comment]
Which iOS version is running on the iPad? Can it be updated?

**Comment by alon112** [comment]
sorry didnt see the respond
IOS 10.3.4.
cant be update anymore :\
from the moment i installed this plugin, on this ipad all the other plugins mark as "No Respons"
but only on this Ipad

**Comment by lukasroegner** [comment]
iOS 10 is really old and does not support "modern" HomeKit accessory types.
I'm sorry but there is no solution for getting it to work with such an old OS version.
