### ISSUE TITLE
Capsule names updated from socket.io

### ISSUE THREAD

**Issue by moodoapplication** [moodoapplication/homebridge-moodo#8]
Dear Lukas,

When switching capsules in Moodo device, it would be great to see the names updated directly, like when changing fan speeds, if possible...

Thanks a lot!

**Comment by lukasroegner** [comment]
Updates of capsule names when capsules are changed works as expected (new data received from the socket within the next minute after changing a capsule). The issue is that the Home app does not update the names of services in the UI immediately.

To see the changes in the Home app, close the details modal, switch to another tab (e.g. "Automation"), then switch back to the "Rooms" or "Home" tab.

Test setup: Home app open, tab "Rooms" open with the room the Moodo is in, Moodo running
1. Remove a capsule
2. Wait a minute or two
3. Switch to tab "Automation"
4. Wait some seconds
5. Switch back to tab "Rooms"
6. Capsule "name" is now "No Capsule"

There is nothing that can really be done, it is a "feature" of the Home app.
